# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json tsconfig.json .
COPY src src
COPY lib lib

RUN npm install

# Default command starts stdio MCP server using tsx
CMD ["npx", "tsx", "src/cli.ts", "stdio"]
